server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: grupo-pagamentos
      auto-offset-reset: latest

kafka:
  topic:
    pagamento: pagamento-topic